# Generated by Django 5.2 on 2025-04-12 19:50
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.apps import apps
User = apps.get_model('invent', 'CustomUser')

def set_default_created_by(apps, schema_editor):
    User = apps.get_model('invent', 'CustomUser')
    default_user = User.objects.get(username='jenil')  # Replace it with a valid user
    StockEntry = apps.get_model('invent', 'StockEntry')
    StockEntry.objects.update(created_by=default_user)

class Migration(migrations.Migration):

    dependencies = [
        ("invent", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AddField(
            model_name="stockentry",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                null=True,  # Make sure it can be null temporarily while we set default
            ),
        ),
        migrations.RunPython(set_default_created_by),  # Set the default user for existing records
    ]
